import { Paper, Typography, IconButton, Tooltip, Divider } from '@mui/material';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { Box } from '@mui/system';
import React from 'react';
import { useParams } from 'react-router';
import useToast from '../hooks/useToast';

const Block = () => {
  const { blockId } = useParams();
  const { setToast } = useToast();
  const truncate = (input) => {
    if (input.length > 15) return `${input.slice(0, 8)}...${input.slice(-7)}`;
    return input;
  };
  const copyText = (e, text) => {
    e.stopPropagation();
    setToast('클립보드에 복사되었습니다.');
    navigator.clipboard.writeText(text);
  };
  return (
    <Box>
      <Typography variant='h4' sx={{ fontWeight: '500' }}>
        Block details
      </Typography>
      <Paper sx={{ mt: 2, p: 2 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Block ID</Typography>
            <p style={{ display: 'flex', alignItems: 'center' }}>
              {truncate(blockId)}
              <Tooltip title='클립보드에 복사'>
                <IconButton size='small' aria-label='copy text' onClick={(e) => copyText(e, blockId)} sx={{ ml: '4px' }}>
                  <ContentCopyIcon style={{ fontSize: '14px' }} />
                </IconButton>
              </Tooltip>
            </p>
          </Box>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Height</Typography>
            <p>20054681</p>
          </Box>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Date</Typography>
            <p>04:36 PM</p>
          </Box>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Confirmations</Typography>
            <p>-6731</p>
          </Box>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Version</Typography>
            <p>2</p>
          </Box>
        </Box>
        <Divider />
        <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 2 }}>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Generated by</Typography>
            <p>panzer</p>
          </Box>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Total forged</Typography>
            <p>1 LSK</p>
          </Box>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Reward</Typography>
            <p>1 LSK</p>
          </Box>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Total burnt</Typography>
            <p>0 LSK</p>
          </Box>
          <Box sx={{ minWidth: '170px' }}>
            <Typography variant='subtitle2'>Total Fee</Typography>
            <p>0 LSK</p>
          </Box>
        </Box>
      </Paper>
    </Box>
  );
};

export default Block;
