import { Typography } from '@mui/material';
import { Box } from '@mui/system';
import React from 'react';
import DataTable from '../components/DataTable';

const columns = [
  { id: 'blockid', label: 'Block ID', minWidth: 170 },
  { id: 'height', label: 'Height', minWidth: 170 },
  { id: 'date', label: 'Date', minWidth: 170 },
  { id: 'generatedby', label: 'Generated By', minWidth: 170 },
  { id: 'transactions', label: 'Transactions', minWidth: 170 },
  { id: 'forged', label: 'Forged', minWidth: 170 },
];

const createCellData = (blockid, height, date, generatedby, transactions, forged) => {
  return { blockid, height, date, generatedby, transactions, forged };
};
const rows = [
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
  createCellData('12583e60daccaa5b2da896920f5864a0dd28613a676a90a44170c5f3846c8448', '20030022', '5/11/2022 - 08:00:10', 'jerry', 0, '1 LSK'),
];
const Blocks = () => {
  return (
    <Box>
      <Typography variant='h4' sx={{ fontWeight: '500', letterSpacing: '1px' }}>
        Blocks
      </Typography>
      <Box sx={{ mt: '12px' }}>
        <DataTable title='Blocks Table' pageId='block' rows={rows} columns={columns} />
      </Box>
    </Box>
  );
};

export default Blocks;
