import React from "react";
import { Card, CardContent, Table, TableBody, TableCell, TableContainer, TableRow, Typography } from "@mui/material";
import SyncAltIcon from '@mui/icons-material/SyncAlt';
import EngineeringIcon from '@mui/icons-material/Engineering';

const DashBoardCard = ({ title, text, rows }) => {
  return (
    <Card sx={{ width: "100%", overflow: "hidden" }}>
      <CardContent>
        <Typography variant="h6" color="textSecondary">
          {title}
        </Typography>
        {title === "Last Transactions" || title === "Last Blocks" ? (
          <TableContainer sx={{ mt: 1 }}>
            <Table sx={{ minWidth: 650 }} aria-label="simple table">
              <TableBody>
                {rows && rows.map((row) => (
                  <TableRow
                    key={row.id}
                    sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
                  >
                    <TableCell component="th" scope="row">
                      {title === "Last Transactions" ? <SyncAltIcon /> : <EngineeringIcon />}
                    </TableCell>
                    <TableCell component="th" scope="row">
                      {row.id.slice(0, 8)}...{row.id.slice(-7)}
                      <br /> {row.date} hours ago
                    </TableCell>
                    <TableCell align="left">
                      {title === "Last Transactions" ? 
                        <>
                          to: {row.sender.slice(0, 8)}...${row.sender.slice(-7)}
                          <br /> from: {row.recipient.slice(0, 8)}...{row.recipient.slice(-7)}
                        </>
                        :
                        <>
                          generated by
                          <br /> {row.generatedby.slice(0, 8)}...{row.generatedby.slice(-7)}
                        </>
                      }
                    </TableCell>
                    <TableCell align="right">
                      {title === "Last Transactions" ?
                        <><span style={{ fontWeight: "bold" }}>{row.amount}</span> <br/> fee: {row.fee}</>
                        :
                        <>1Ⱡ</>
                      }
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        ) : (
          <Typography variant="h4" color="inherit">
            {text}
          </Typography>
        )}
      </CardContent>
    </Card>
  );
};

export default DashBoardCard;
